// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview An AML transaction flagging AI agent.
 *
 * - flagAMLTransactions - A function that handles the AML transaction flagging process.
 * - FlagAMLTransactionsInput - The input type for the flagAMLTransactions function.
 * - FlagAMLTransactionsOutput - The return type for the flagAMLTransactions function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const FlagAMLTransactionsInputSchema = z.object({
  transactionDetails: z
    .string()
    .describe('Details of the transaction, including sender, receiver, amount, and timestamp.'),
  userProfile: z.string().describe('The user profile of the transaction sender.'),
});
export type FlagAMLTransactionsInput = z.infer<typeof FlagAMLTransactionsInputSchema>;

const FlagAMLTransactionsOutputSchema = z.object({
  isSuspicious: z.boolean().describe('Whether or not the transaction is suspicious.'),
  reason: z.string().describe('The reason for flagging the transaction as suspicious.'),
  suggestedActions: z
    .array(z.string())
    .describe('Suggested actions for further review, such as contacting the user or filing a SAR.'),
});
export type FlagAMLTransactionsOutput = z.infer<typeof FlagAMLTransactionsOutputSchema>;

export async function flagAMLTransactions(input: FlagAMLTransactionsInput): Promise<FlagAMLTransactionsOutput> {
  return flagAMLTransactionsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'flagAMLTransactionsPrompt',
  input: {schema: FlagAMLTransactionsInputSchema},
  output: {schema: FlagAMLTransactionsOutputSchema},
  prompt: `You are an expert AML analyst specializing in flagging suspicious transactions.

You will use the transaction details and user profile to determine if the transaction is suspicious.

Transaction Details: {{{transactionDetails}}}
User Profile: {{{userProfile}}}

Based on the transaction details and user profile, determine if the transaction is suspicious and provide a reason.
Also, suggest actions for further review, such as contacting the user or filing a SAR. Set the isSuspicious output field appropriately.

Consider these factors when assessing the transaction:
- Transaction amount and frequency
- Geographic location of the transaction
- Relationship between sender and receiver
- User's past transaction history
- Any unusual or inconsistent activity

Output the results in JSON format.`, // Use JSON format for the output.
});

const flagAMLTransactionsFlow = ai.defineFlow(
  {
    name: 'flagAMLTransactionsFlow',
    inputSchema: FlagAMLTransactionsInputSchema,
    outputSchema: FlagAMLTransactionsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
